openapi: 3.0.2
info:
  title: SDNNT API
  description: |-

    API přístupné pouze pro uživatele s vygenerovaným platným API-KEY.
    Umožňuje spravovat nahlížet do katalogu, zobrazovat vlastní žádosti na vyřazení
    nebo požadavky na zařazení díla na seznam DNNT
  version: 1.0.0

externalDocs:
  description: Odkaz na stranky sdnnt
  url: 'https://sdnnt.nkp.cz'
servers:
  - url: ../api/v1.0
tags:
  - name: Požadavky
    description: Endpoint, který řeší kompletně správu požadavků
  - name: Katalog
    description: Endpoint pro hledání v katalogu

paths:

  /catalog:
    get:
      tags:
        - Katalog
      summary: Základní funkcionalita pro nahlížení do katalogu
      description: Poskytuje základní funkcionalitu pro nahlížení do katalogu
      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
        - in: query
          name: state
          schema:
            type: string
            enum: ["PA","A","VS","VN","N","NZN","VVN","VVS","NZ"]
          required: false
        - in: query
          name: license
          schema:
            type: string
            enum: ["dnntt","dnnto"]
          required: false
        - in: query
          name: rows
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false


      responses:
        '200':
          description: Záznamy z katalogu
          content:
            application/json:
              schema:
                type: object
                properties:
                  requests:
                    type: array
                    items:
                      $ref: './schemas/catalog/CatalogResponse.yaml'
      security:
        - api_key: []


  /request:
    get:
      tags:
        - Požadavky
      summary: Vrací všechny žádosti pro uživatele
      description: Vrací všechny žádosti, případně filtrované dle stavu
      operationId: requestGet
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: ["open","waiting","processed","rejected","approved"]
          required: false
        - in: query
          name: navrh
          schema:
            type: string
            enum: ["NZN","VVS"]
          required: false
      responses:
        '200':
          description: Všechny uložené žádosti
          content:
            application/json:
              schema:
                $ref: './schemas/requests/ArrayOfSavedRequest.yaml'
      security:
        - api_key: []


  /request/batch/nzn:
    put:
      tags:
        - Požadavky
      summary: Podání jednoho nebo více návhrhů na zařazení do seznamu DNNT
      description: Řeší hromadné podání navrhů na zařazení do seznamu DNNT
      operationId: requestBatchNzn
      requestBody:
        description: Hromadný návrh (jeden nebo více, identifikátory musí existovat a nesmí se opakovat)
        content:
          application/json:
            schema:
              #$ref: '#/components/schemas/BatchRequest'
              $ref: './schemas/requests/BatchRequest.yaml'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                #$ref: '#/components/schemas/BatchResponse'
                $ref: './schemas/requests/BatchResponse.yaml'
        '400':
          description: Špatný dotaz (syntaxe atd..)
        '404':
          description: Identifikátory nenalezen(y)
        '405':
          description: Chyba validace (datumy atd..)

      security:
        - api_key: []

  /request/batch/vvs:
    put:
      tags:
        - Požadavky
      summary: Požadavek případně více požadavků na vyřazení díla ze seznamu DNNT
      description: Řeší hromadnou hroadný požadavek o vyřazení ze seznamu DNNT
      operationId: requestBatchVvs
      requestBody:
        description: Hromadný požadavek (jeden nebo více, identifikátory musí existovat a nesmí se opakovat)
        content:
          application/json:
            schema:
              $ref: './schemas/requests/BatchRequest.yaml'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: './schemas/requests/BatchResponse.yaml'
        '400':
          description: Špatný dotaz (syntaxe atd..)
        '404':
          description: Identifikátory nenalezen(y)
        '405':
          description: Chyba validace (datumy atd..)

      security:
        - api_key: []

components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
