openapi: 3.0.2
info:
  title: SDNNT API
  description: |

    API přístupné pouze pro uživatele s vygenerovaným platným API-KEY.

    Umožňuje následující:
      - Nahlížet a vyhledávat v katalogu
      - Zobrazit a filtrovat všechny uživatelské návrhy
      - Podávat hromadné požadavky a návrhy na zařazení resp. vyřazení díla ze seznamu.

  version: 1.0.0

externalDocs:
  description: Externí dokumentace k projektu
  url: 'https://sdnnt.nkp.cz'

servers:
  - url: ../api/v1.0
tags:
  - name: Požadavky
    description: Endpoint, který řeší kompletně správu požadavků
  - name: Katalog
    description: Endpoint pro hledání v katalogu

paths:

  /catalog:
    get:
      tags:
        - Katalog
      summary: Nahlížení do katalogu
      description: |
        Umožňuje vyhledávat a prohlížet data v katalogu. Předdefinované filtry
          - Licence - licence díla (**DNNTT**, **DNNTO**)
          - Stavy - Stav díla (**A**, **PA**, **VS**, **VN**, **N**, **NZN**, **VVN**, **VVS**, **NZ**)

      parameters:
        - in: query
          name: query
          schema:
            type: string
          required: true
        - in: query
          name: state
          schema:
            type: string
            enum: ["A","PA","V","VS","VN","N","NZ"]
          required: false
        - in: query
          name: license
          schema:
            type: string
            enum: ["dnntt","dnnto"]
          required: false
        - in: query
          name: fullCatalog
          schema:
            type: boolean
            default: false
          required: false
        - in: query
          name: rows
          schema:
            type: integer
            minimum: 1
            maximum: 100
            default: 20
          required: false
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          required: false


      responses:
        '200':
          description: Záznamy z katalogu
          content:
            application/json:
              schema:
                $ref: './schemas/catalog/CatalogResponse.yaml'
      security:
        - api_key: []


  /request:
    get:
      tags:
        - Požadavky
      summary: Návrhy a požadavky
      description: Vrací všechny návrhy a požadavky pro konkrétního uživatele, umožňuje filtrovat dle stavu
      operationId: requestGet
      parameters:
        - in: query
          name: status
          schema:
            type: string
            enum: ["open","waiting","processed"]
          required: false
        - in: query
          name: navrh
          schema:
            type: string
            enum: ["NZN","VVS", "VVN"]
          required: false
      responses:
        '200':
          description: Všechny uložené žádosti
          content:
            application/json:
              schema:
                $ref: './schemas/requests/ArrayOfSavedRequest.yaml'
      security:
        - api_key: []


  /request/batch/nzn:
    put:
      tags:
        - Požadavky
      summary: Hromadný návrh k zařazení do seznamu
      description: |
        Řeší návrh k zařazení na seznam.
          - Může obsahovat jednu nebo více dávek a v každé dávce musí být minimálně obsaženo jedno dílo.
          - Dílo je identifikováno identifikátorem ze souborného katalogu.
          - Dílo musí být ve stavu **N** případně **VN**
      operationId: requestBatchNzn
      requestBody:
        description: Hromadný návrh (jeden nebo více, identifikátor musí existovat v souborném katalogu, dokument u sebe musí mít přítomné pole stavů marc_911a)
        content:
          application/json:
            schema:
              #$ref: '#/components/schemas/BatchRequest'
              $ref: './schemas/requests/BatchRequest.yaml'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting. V poli  **saved** jsou uloženy dávky, které se podařilo uložit. V poli  **notsaved** jsou dávky, které se nepodařilo uložit.
          content:
            application/json:
              schema:
                #$ref: '#/components/schemas/BatchResponse'
                $ref: './schemas/requests/BatchResponse.yaml'
        '400':
          description: Špatný dotaz (syntaxe atd..)

      security:
        - api_key: []

  /request/batch/vvs:
    put:
      tags:
        - Požadavky
      summary: Výzva k vyřazení ze seznamu
      description: |
        Řeší hromadnou výzvu k vyřazení ze seznamu.
          - Může obsahovat jednu nebo více dávek a v každé dávce musí být minimálně obsaženo jedno dílo.
          - Dílo je identifikováno identifikátorem ze souborného katalogu.
          - Dílo musí být ve stavu **A**
      operationId: requestBatchVvs
      requestBody:
        description: Hromadná výzva (jedna nebo více, identifikátor musí existovat v souborném katalogu, dokument u sebe musí mít přítomné pole stavů marc_911a)
        content:
          application/json:
            schema:
              $ref: './schemas/requests/BatchRequest.yaml'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: './schemas/requests/BatchResponse.yaml'
        '400':
          description: Špatný dotaz (syntaxe atd..)

      security:
        - api_key: []


  /request/batch/vvn:
    put:
      tags:
        - Požadavky
      summary: Výzva k vyřazení z Návrhu seznamu
      description: |
        Řeší hromadnou hromadný požadavek o vyřazení z návrhu ze seznamu.
          - Může obsahovat jednu nebo více dávek a v každé dávce musí být minimálně obsaženo jedno dílo.
          - Dílo je identifikováno identifikátorem ze souborného katalogu.
          - Dílo musí být ve stavu **PA**

      operationId: requestBatchVvn
      requestBody:
        description: Hromadná výzva(jedna nebo více, identifikátor musí existovat v souborném katalogu, dokument u sebe musí mít přítomné pole stavů marc_911a)
        content:
          application/json:
            schema:
              $ref: './schemas/requests/BatchRequest.yaml'
        required: true

      responses:
        '200':
          description: Žádost vytvořena a ve stavu waiting
          content:
            application/json:
              schema:
                $ref: './schemas/requests/BatchResponse.yaml'
        '400':
          description: Špatný dotaz (syntaxe atd..)

      security:
        - api_key: []


components:
  securitySchemes:
    api_key:
      type: apiKey
      name: X-API-KEY
      in: header
      description: Přihlášení pomocí API klíče. Musí být přiděleno administrátorem.
