openapi: 3.0.2
info:
  title: SDNNT API
  description: |-

    API přístupné všem. Umožňuje získávat aktuální seznam děl označených licencí:

      - **DNNTO**
      - **DNNTT**

    Pro jednotlivé dotazy není potřeba přihlášení.

    Endpointy mohou v případech velkého zatížení vracet status 429 - Too many requests.

  version: 1.0.0
externalDocs:
  description: Odkaz na str
  url: 'https://sdnnt.nkp.cz'
servers:
  - url: ../api/v1.0
tags:
  - name: SeznamyDNNT
    description: Exporty del uvedenych na seznamu dnnt
paths:
  # Seznamy del zarazenych na dnntt
  /lists/dnntt/csvexport:
    get:
      tags:
        - SeznamyDNNT
      summary: Export dat pro licenci dnntt
      description: Export data, licence **DNNTT**
      operationId: listDnnttCsv
      parameters:
        - in: query
          name: institution
          description: Sigla instituce. (ABA001, ABA007, atd...)
          schema:
            type: string
            example: ABA001
          required: false
        - in: query
          name: from
          description: Datum změny záhznamu. Vrací pouze ty záznamy, které se změnily.
          schema:
            type: string
            format: date-time
            example: "2021-07-27T16:31:05.169Z"
          required: false
        - in: query
          name: removeduplicatesuuid
          description: Filtruje stejne uuid. (Objevuje se zejmena pokud je stejny dokument ve dvou ruznych institicich)
          schema:
            type: boolean
            default: false
          required: false
      responses:
        '200':
          description: Export byl vytvořen
          content:
            application/csv:
              schema:
                type: string
        '429':
          description: Server je plně vytížen, opakujte dotaz později

  # Seznamy del zarazenych na dnntt
  /lists/dnnto/csvexport:
    get:
      tags:
        - SeznamyDNNT
      summary: Export dat pro licenci dnntto
      description: Export dat, licence **DNNTO**
      operationId: listDnntoCsv
      parameters:
        - in: query
          name: institution
          description: Sigla instituce. (ABA001, ABA007, atd...)
          schema:
            type: string
            example: ABA001
          required: false
        - in: query
          name: from
          description: Datum změny záhznamu. Vrací pouze ty záznamy, které se změnily.
          schema:
            type: string
            format: date-time
            example: "2021-07-27T16:31:05.169Z"
          required: false
        - in: query
          name: removeduplicatesuuid
          description: Filtruje stejne uuid. (Objevuje se zejmena pokud je stejny dokument ve dvou ruznych institicich).
          schema:
            type: boolean
            default: false
          required: false
      responses:
        '200':
          description: Export byl vytvořen
          content:
            application/csv:
              schema:
                type: string
        '429':
          description: Server je plně vytížen, opakujte dotaz později

