version: "2"
services:
  sdnnt-tomcat:
    image: sdnnt:latest
    ports:
        - '8080:8080'
    volumes:
        - ./data/config:/opt/app-root/src/.sdnnt
        - ./data/logs:/usr/local/tomcat/logs

  sdnnt-solr:
    image: bitnami/solr:latest
    volumes:
        - ./data/solr-persistence:/bitnami
    ports:
        - '8983:8983'


