version: "2"
services:
  sdnnt-tomcat:
    image: sdnnt:latest
    ports:
        - '8080:8080'
    volumes:
        - ./config:/opt/app-root/src/.sdnnt
  sdnnt-solr:
    image: sdnnt-solr:8.11
    ports:
        - '8983:8983'
