/*
 * SDNNT API
 *  POPIS API publikovaneho api 
 *
 * OpenAPI spec version: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package cz.inovatika.sdnnt.openapi.endpoints.model;

import java.util.Objects;
import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import java.util.ArrayList;
import java.util.List;
import javax.validation.Valid;

/**
 * AllRequestsResponse
 */
@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.JavaJerseyServerCodegen", date = "2021-07-09T09:07:54.515Z[GMT]")public class AllRequestsResponse   {
  @JsonProperty("saved")
  private List<SavedRequest> saved = null;

  public AllRequestsResponse saved(List<SavedRequest> saved) {
    this.saved = saved;
    return this;
  }

  public AllRequestsResponse addSavedItem(SavedRequest savedItem) {
    if (this.saved == null) {
      this.saved = new ArrayList<SavedRequest>();
    }
    this.saved.add(savedItem);
    return this;
  }

  /**
   * Get saved
   * @return saved
   **/
  @JsonProperty("saved")
  @Schema(description = "")
  @Valid
  public List<SavedRequest> getSaved() {
    return saved;
  }

  public void setSaved(List<SavedRequest> saved) {
    this.saved = saved;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AllRequestsResponse allRequestsResponse = (AllRequestsResponse) o;
    return Objects.equals(this.saved, allRequestsResponse.saved);
  }

  @Override
  public int hashCode() {
    return Objects.hash(saved);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AllRequestsResponse {\n");
    
    sb.append("    saved: ").append(toIndentedString(saved)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }
}
